version: '3.7'
services:
  laurelwoods-postgresql:
    image: postgres
    container_name: laurelwoods-postgresql
    restart: always
    volumes:
      #- laurelwoods_volume_postgres:/var/lib/postgresql/data
      - ex:/var/lib/postgresql/data
    #ports:
    #  - 5432:5432
    environment:
      - POSTGRES_DB=laurelwoods_db
      - POSTGRES_USER=laurelwoods
      - POSTGRES_PASSWORD=laurelwoods
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
      
  laurelwoods-backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: laurelwoods-backend 
    volumes: 
      - ./backend/laurelwoods_backend:/home/laurelwoods_backend
    ports: 
      - "8888:8888"
    command: gunicorn laurelwoods_backend.wsgi:application --workers 5 --bind 0.0.0.0:8888
    depends_on:
      - laurelwoods-postgresql

  laurelwoods-nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: laurelwoods-nginx
    ports: 
      - "80:80"
    depends_on:
      - laurelwoods-backend
    
volumes:
  ex: